export const PERMISSION = Object.freeze({
    DASHBOARD: "dashboard",
    ANALYTICS: "analytics",
    TRANSAKSI: "transaksi",
    INVENTORY: "inventory",
    RESERVASI: "reservasi",
    CATALOG: "catalog_menu",
    SCRAP: "scrap_monitoring",
    SPP: "spp",
    PRINT_BARCODE: "print_barcode",
    MASTER_BARANG: "master_barang",
    CANCEL_TX: "cancel_tx",
    USER_MANAGEMENT: "user_management",
    PHOTO_PREVIEW: "photo_preview",
    PHOTO_UPDATE: "photo_update",
    LOCATION_UPDATE: "location_update",
    MASTER_CREATE: "master_create",
    MASTER_IMPORT: "master_import",
    CATALOG_FOLDER_MANAGE: "catalog_folder_manage",
    SCRAP_EDIT: "scrap_edit",
    SCRAP_DELETE: "scrap_delete",
    VIEW_STOCK: "view_stock",
    VIEW_ACTION: "view_action",
    EXPORT_EXCEL: "export_excel",
    EDIT_ITEM: "edit_item",
    DELETE_ITEM: "delete_item",
    TOGGLE_STATUS: "toggle_status"
});
