function drawFormToPDF(
    doc,
    items,
    startY,
    dept,
    tgl,
    resv,
    noDoc,
    pageNum,
    userName,
    totalPages
) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.text("PT BINTANG INDOKARYA GEMILANG", 10, startY);

    doc.rect(170, startY - 4, 30, 6);
    doc.text(`No. Doc: #${noDoc}`, 171, startY);

    doc.setFontSize(14);
    doc.text("BUKTI PERMINTAAN SUKU CADANG", 105, startY + 8, { align: "center" });
    doc.line(10, startY + 10, 200, startY + 10);

    doc.setFontSize(9);
    doc.text(`DEPT: ${dept}`, 10, startY + 20);
    doc.text(`TGL: ${tgl}`, 85, startY + 20);
    doc.text(`RESV: ${resv}`, 155, startY + 20);

    let currentY = startY + 25;
    const colX = [10, 35, 93, 105, 120, 135, 165, 200];

    doc.setFillColor(240, 240, 240);
    doc.rect(10, currentY, 190, 7, "F");
    doc.rect(10, currentY, 190, 7);

    colX.forEach((x) => doc.line(x, currentY, x, currentY + 7));

    doc.setFontSize(7);
    doc.text("Kode", 12, currentY + 5);
    doc.text("Nama Suku Cadang", 37, currentY + 5);
    doc.text("Sat", 95, currentY + 5);
    doc.text("Qty", 108, currentY + 5);
    doc.text("Real", 124, currentY + 5);
    doc.text("No. Mesin", 137, currentY + 5);
    doc.text("Keterangan", 167, currentY + 5);

    doc.setFont("helvetica", "normal");

    const displayItems = [...items];
    while (displayItems.length < 8) {
        displayItems.push({});
    }

    displayItems.forEach((item) => {
        currentY += 7;

        doc.rect(10, currentY, 190, 7);
        colX.forEach((x) => doc.line(x, currentY, x, currentY + 7));

        if (item.kode) {
            doc.text(String(item.kode), 11, currentY + 5);
            doc.text(String(item.nama || "").substring(0, 32), 36, currentY + 5);
            doc.text(String(item.satuan || ""), 94, currentY + 5);
            doc.text(String(item.qty || "0"), 108, currentY + 5, { align: "center" });
            doc.text(String(item.noMesin || ""), 136, currentY + 5);
            doc.text(
                String(item.keterangan || "").substring(0, 20),
                166,
                currentY + 5
            );
        }
    });

    const sigY = startY + 105;
    const roles = [
        { l: "Diminta Oleh,", n: userName || "..............." },
        { l: "Diketahui Oleh,", n: "..............." },
        { l: "Disetujui Oleh,", n: "..............." },
        { l: "Diserahkan Oleh,", n: "..............." },
    ];

    roles.forEach((role, i) => {
        const xPos = 15 + i * 48;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(8);
        doc.text(role.l, xPos + 10, sigY, { align: "center" });

        doc.text(role.n.toUpperCase(), xPos + 10, sigY + 22, { align: "center" });
        doc.line(xPos, sigY + 18, xPos + 25, sigY + 18);
    });

    doc.setFontSize(6);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(150, 150, 150);

    const footerY = startY + 132;

    doc.text(`Generated by WMS - Hal ${pageNum} / ${totalPages}`, 10, footerY);

    const now = new Date();
    const dateStr = now.toLocaleDateString("id-ID");
    const timeStr = now.toLocaleTimeString("id-ID", {
        hour: "2-digit",
        minute: "2-digit",
    });
    doc.text(`Dicetak pada: ${dateStr} ${timeStr}`, 200, footerY, {
        align: "right",
    });
    doc.setTextColor(0, 0, 0);
}

export function downloadBONPDF({
    paginatedItems,
    txDept,
    txTanggal,
    txReservasi,
    docNumber,
    userData
}) {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF('p', 'mm', 'a4');

    const dept = (txDept || "-").toUpperCase();
    const tgl = txTanggal || "-";
    const resv = (txReservasi || "-").toUpperCase();
    const noDoc = docNumber || new Date().getTime().toString().substring(7);
    const userName = userData?.nama || "............";

    const allPages = paginatedItems;
    if (allPages.length === 0) return;

    for (let i = 0; i < allPages.length; i += 2) {
        if (i > 0) doc.addPage();

        drawFormToPDF(doc, allPages[i], 10, dept, tgl, resv, noDoc, i + 1, userName, allPages.length);

        doc.setDrawColor(200, 200, 200);
        doc.setLineDashPattern([2, 2], 0);
        doc.line(5, 148.5, 205, 148.5);
        doc.setLineDashPattern([], 0);
        doc.setDrawColor(0, 0, 0);

        if (allPages[i + 1]) {
            drawFormToPDF(doc, allPages[i + 1], 158, dept, tgl, resv, noDoc, i + 2, userName, allPages.length);
        }
    }

    doc.save(`BON BPSC_${dept}_${noDoc}.pdf`);
}